version: '2'

services:
  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  mysql:
    image: "mysql/mysql-server"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=iotsuite
      - MYSQL_USER=iotsuite
      - MYSQL_PASSWORD=iotsuite

  nats:
    image: "nats"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto:/mosquitto"
    
